### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by leonardo-max** [jpedroschmitz/gobarber#1]
Olá @jpedroschmitz fiz um checkout para testar sua aplicação porém não consegui encontrar o repositorio da API que na documentação esta apontando para: https://github.com/jpedroschmitz/gobarber-api

**Comment by jpedroschmitz** [comment]
Olá @Leonardo-Max, eu ainda estou documentando a API, e, por isso, ainda não subi a mesma para o GitHub, mas, assim que eu terminar te aviso aqui.

**Comment by jpedroschmitz** [comment]
@Leonardo-Max, subi agora há pouco a API para o GitHub com toda a documentação completa. Se você tiver algum problema ao rodar a mesma por favor me avise. Eu vou fechar essa issue visto que a questão foi resolvida.
